
name: 'Update Github Releases'

on:
  repository_dispatch:
    types:
      - update-github-releases
  workflow_dispatch:
  schedule:
    - cron:  '30 4,16 * * *'

permissions:
  contents: write

jobs:
  update_github_releases:
    name: Update Github Release Index
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    concurrency:
      group: update-releases
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run index-github-releases
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
        with:
          commit_message: Updated Github Release-Index

